services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?error}
      - DATABASE_PATH=/db/doneosaur.db
      - PHX_HOST=${PHX_HOST:?"set PHX_HOST"}
      - TZ=America/Los_Angeles
    restart: always
    volumes:
      - ./data:/db
